---
- name: Check if yq {{ yq_version }} is installed
  shell: yq --version || true
  register: yq_check
  changed_when: false

- name: Install yq
  get_url:
    url: "{{ yq_dl_url }}"
    dest: "{{ yq_path }}"
    force: true
    owner: root
    group: root
    mode: 0755
  when: >
    yq_check.stdout_lines | length == 0
    or yq_version not in yq_check.stdout_lines[0]

- name: Configure Bash completion
  shell: >
    yq shell-completion bash > /etc/bash_completion.d/yq
  when: >
    yq_check.stdout_lines | length == 0
    or yq_version not in yq_check.stdout_lines[0]
