---
- name: Install repository key
  ansible.builtin.get_url:
    url: "{{ brave_apt_repo_key_url }}"
    dest: "{{ brave_apt_repo_key_file }}"
    force: true
    owner: root
    group: root
    mode: "0644"
  tags:
    - brave:repo
    - brave:install

- name: Configure repository
  ansible.builtin.apt_repository:
    repo: "{{ brave_apt_repo_line }}"
    filename: "{{ brave_apt_repo_file }}"
    state: present
    update_cache: true
  tags:
    - brave:repo
    - brave:install

- name: Install packages
  ansible.builtin.apt:
    name: brave-browser
    state: present
    install_recommends: false
  tags: brave:install
