---
- name: Check if processor supports virtualization
  ansible.builtin.shell: >
    grep -E --count '(vmx|svm)' /proc/cpuinfo || true
  changed_when: false
  register: _kvm_check
  tags: kvm:install

- name: Fail if processor does not support virtualization
  ansible.builtin.fail:
    msg: The machine processor does not support virtualization.
  when: _kvm_check.stdout == "0"
  tags: kvm:install

- name: Install server packages
  ansible.builtin.apt:
    name:
      - bridge-utils
      - libvirt-clients
      - libvirt-daemon-system
      - qemu-kvm
    state: present
  when: kvm_server_mode | bool
  tags: kvm:install

- name: Install Virtual Machine Manager (virt-manager)
  ansible.builtin.apt:
    name:
      - virt-manager
      - gir1.2-spiceclientgtk-3.0
      - ssh-askpass-gnome
    state: present
    install_recommends: false
  when: kvm_install_virt_manager | bool
  tags: kvm:install

- name: Install client utilities
  ansible.builtin.apt:
    name:
      - cloud-image-utils
      # 'mkisofs' is required by 'libvirt_cloudinit_disk' Terraform resource
      # Ref: https://registry.terraform.io/providers/dmacvicar/libvirt/latest/docs/resources/cloudinit
      - genisoimage
    state: present
  when: kvm_install_client_utilities | bool
  tags: kvm:install

- name: Add users to KVM system groups
  ansible.builtin.user:
    name: "{{ item }}"
    groups:
      - kvm
      - libvirt
    append: true
  loop: "{{ kvm_users }}"
  tags: kvm:config

# Avoid permission error on '/var/lib/libvirt/images' when using Terraform libvirt provider
# Ref: https://github.com/dmacvicar/terraform-provider-libvirt/issues/546#issuecomment-612983090
- name: Disable libvirt QEMU security driver
  ansible.builtin.lineinfile:
    path: /etc/libvirt/qemu.conf
    regexp: "^(# *)?security_driver .*"
    line: security_driver = "none"
  notify: Restart libvirtd
  tags: kvm:config

- name: Install kvm-import-volume script
  ansible.builtin.copy:
    src: kvm-import-volume.sh
    dest: /usr/local/bin/kvm-import-volume
    owner: root
    group: root
    mode: "0755"
  tags: kvm:import-volume
