---
- name: Ensure all utilities are installed
  pip:
    name: "{{ item.1.name | default(item.1) }}"
    version: "{{ item.1.version | default(omit) }}"
    state: present
    virtualenv: "{{ piputils_install_dir }}/{{ item.0.name }}"
    virtualenv_command: python3 -m venv --upgrade "{{ piputils_install_dir }}/{{ item.0.name }}"
  loop: "{{ piputils_packages | subelements('packages') }}"
  loop_control:
    label: "{{ item.1.name | default(item.1) }}"
  when: item.0.name not in piputils_uninstall_package_names
  register: piputils_output
  changed_when: >
    "Requirement already satisfied: " + item.1.name | default(item.1) not in piputils_output.stdout

- name: Ensure all utilities' symlinks exist
  file:
    src: "{{ piputils_install_dir }}/{{ item.0.name }}/bin/{{ item.1 }}"
    path: "{{ piputils_bin_symlink_dir }}/{{ item.1 }}"
    state: link
    force: false
  loop: "{{ piputils_packages | subelements('binaries') }}"
  loop_control:
    label: "{{ item.0.name }} - {{ item.1 }}"
  when: item.0.name not in piputils_uninstall_package_names
