---
- name: Uninstall selected utilities' binaries
  file:
    path: "{{ piputils_bin_symlink_dir }}/{{ item.1 }}"
    state: absent
  loop: "{{ piputils_uninstall_packages | subelements('binaries') }}"

- name: Uninstall selected utilities' directories
  file:
    path: "{{ piputils_install_dir }}/{{ item.name }}"
    state: absent
  loop: "{{ piputils_uninstall_packages }}"
