---
- name: Check if version {{ rclone_version }} is installed
  ansible.builtin.shell: dpkg-query --showformat='${Version}' --show rclone || true
  register: rclone_check
  changed_when: false

- name: Install package
  ansible.builtin.apt:
    deb: "{{ rclone_package_url }}"
    state: present
    install_recommends: false
  when: rclone_check.stdout != rclone_version

- name: Configure Bash completion
  ansible.builtin.command: >
    rclone completion bash /etc/bash_completion.d/rclone
  when:
    - rclone_check.stdout != rclone_version
    - rclone_enable_bash_completion | bool
