---
- name: Instala chave do repositório
  apt_key:
    url: "{{ postgres_repo_key_url }}"
    id: "{{ postgres_repo_key }}"
    state: present

- name: Configura repositório
  apt_repository:
    repo: "{{ postgres_repo_line }}"
    filename: "{{ postgres_repo_file }}"
    state: present
    update_cache: true
