---
- name: Check if Chrome is installed
  ansible.builtin.shell: dpkg-query --showformat='${Version}' --show google-chrome-stable || true
  register: chrome_check
  changed_when: false

- name: Install package
  ansible.builtin.apt:
    deb: "{{ chrome_package_url }}"
    state: present
    install_recommends: false
  when: "'no packages found matching' in chrome_check.stderr"
