---
- name: Check if Extension Pack is installed
  shell: >
    set -o pipefail &&
    vboxmanage list extpacks | grep '^Version:.*{{ virtualbox_extpack_version }}$'
  args:
    executable: /bin/bash
  register: virtualbox_check_extpack
  failed_when: virtualbox_check_extpack.rc > 1
  changed_when: false
  tags: virtualbox:extpack

- name: Download Extension Pack
  get_url:
    url: "{{ virtualbox_extpack_url }}"
    dest: "{{ virtualbox_extpack_dl_file }}"
  when: virtualbox_check_extpack.rc == 1
  tags: virtualbox:extpack

- name: Install Extension Pack
  shell: >
    set -o pipefail &&
    echo yes | vboxmanage extpack install --replace {{ virtualbox_extpack_dl_file }}
  args:
    executable: /bin/bash
  when: virtualbox_check_extpack.rc == 1
  tags: virtualbox:extpack
