---
- name: Check if version {{ bat_version }} is installed
  ansible.builtin.shell: dpkg-query --showformat='${Version}' --show bat || true
  register: bat_check
  changed_when: false

- name: Install package
  ansible.builtin.apt:
    deb: "{{ bat_package_url }}"
    state: present
    install_recommends: false
  when: bat_check.stdout != bat_version

- name: Disable package installation from Ubuntu repos
  ansible.builtin.copy:
    content: |
      # Managed by Ansible
      Package: bat
      Pin: release o=Ubuntu
      Pin-Priority: -1
    dest: /etc/apt/preferences.d/bat
    owner: root
    group: root
    mode: "0644"
