---
piputils_install_dir: /opt/ansible-piputils

piputils_bin_symlink_dir: /usr/local/bin

# piputils_packages:
# - name: example
#     packages:
#       - name: example
#         version: 1.0.0
#     binaries:
#       - example
piputils_packages:
  - name: bump2version
    packages:
      - name: bump2version
        version: 1.0.1
    binaries:
      - bump2version
  # - name: cookiecutter
  #   packages:
  #     - name: cookiecutter
  #       version: 2.1.1
  #   binaries:
  #     - cookiecutter
  # - name: httpie
  #   packages:
  #     - name: httpie
  #       version: 3.2.1
  #     - name: httpie-edgegrid
  #       version: 2.1.1
  #     - name: httpie-jwt-auth
  #       version: 0.4.0
  #   binaries:
  #     - http
  #     - https
  # - name: keyring
  #   packages:
  #     - name: keyring
  #       version: 23.11.0
  #   binaries:
  #     - keyring
  - name: pre-commit
    packages:
      - name: pre-commit
        version: 3.7.0
    binaries:
      - pre-commit
  - name: ps_mem
    packages:
      - name: ps_mem
        version: 3.14
    binaries:
      - ps_mem
  # - name: pygments
  #   packages:
  #     - name: Pygments
  #       version: 2.13.0
  #   binaries:
  #     - pygmentize
  # - name: speedtest-cli
  #   packages:
  #     - name: speedtest-cli
  #       version: 2.1.3
  #   binaries:
  #     - speedtest-cli
  # - name: yamale
  #   packages:
  #     - name: yamale
  #       version: 4.0.4
  #   binaries:
  #     - yamale
  # - name: yamllint
  #   packages:
  #     - name: yamllint
  #       version: 1.27.1
  #   binaries:
  #     - yamllint

# piputils_uninstall_packages:
#   - name: glances
#     binaries:
#       - glances
piputils_uninstall_packages: []
