---
jq_version: "1.6"

jq_dl_url: https://github.com/stedolan/jq/releases/download/jq-{{ jq_version }}/jq-linux64

jq_path: /usr/local/bin/jq

jq_man_dl_url: >-
  https://raw.githubusercontent.com/stedolan/jq/jq-{{ jq_version }}/jq.1.prebuilt

jq_man_path: /usr/local/share/man/man1/jq.1
