---
# Ref: https://support.mozilla.org/en-US/kb/install-firefox-linux#w_install-firefox-deb-package-for-debian-based-distributions

firefox_apt_repo_key_url: https://packages.mozilla.org/apt/repo-signing-key.gpg

firefox_apt_repo_key_file: /etc/apt/keyrings/packages.mozilla.org.asc

firefox_apt_repo_line: deb [signed-by={{ firefox_apt_repo_key_file }}] https://packages.mozilla.org/apt mozilla main

firefox_apt_repo_file: mozilla

firefox_set_as_default_browser: true
