---
bat_version: 0.24.0

bat_package_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

bat_package_url: >-
  https://github.com/sharkdp/bat/releases/download/v{{ bat_version }}/bat_{{ bat_version }}_{{ bat_package_arch }}.deb
