---
- name: Verifica se MEGAsync está instalado
  shell: dpkg-query --showformat='${Version}' --show megasync || true
  register: megasync_check
  changed_when: false

- name: Instala MEGAsync
  apt:
    deb: "{{ megasync_package_url }}"
    state: present
    install_recommends: false
  when: "'no packages found matching' in megasync_check.stderr"
