---
- name: Install repository keys
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
    keyring: /etc/apt/trusted.gpg.d/{{ slack_repo_filename }}.gpg
  loop: "{{ slack_repo_key_urls }}"
  tags:
    - slack:repo
    - slack:install

- name: Configure repository
  ansible.builtin.apt_repository:
    repo: "{{ slack_repo_line }}"
    filename: "{{ slack_repo_filename }}"
    state: present
    update_cache: true
  tags:
    - slack:repo
    - slack:install

- name: Configure package defaults
  ansible.builtin.copy:
    content: |
      repo_add_once="true"
      repo_reenable_on_distupgrade="true"
    dest: /etc/default/slack
    owner: root
    group: root
    mode: "0644"
  tags:
    - slack:repo
    - slack:install

- name: Install package
  ansible.builtin.apt:
    name: slack-desktop
    state: present
    install_recommends: false
  tags: slack:install
