---
- name: Verifica se Terraform {{ terraform_version }} está instalado
  shell: terraform version || true
  register: terraform_check
  changed_when: false

- name: Instala Terraform
  unarchive:
    remote_src: true
    src: "{{ terraform_dl_url }}"
    dest: "{{ terraform_path | dirname }}"
    owner: root
    group: root
    mode: "0755"
  when: >
    terraform_check.stdout_lines | length == 0
    or terraform_version not in terraform_check.stdout_lines[0]

- name: Instala Bash completion
  get_url:
    url: "{{ terraform_completion_url }}"
    dest: /etc/bash_completion.d/terraform
    owner: root
    group: root
    mode: "0644"
  tags: terraform:completion

- name: Cria arquivo de configuração
  copy:
    src: terraformrc
    dest: "{{ terraform_config_file }}"
    owner: "{{ terraform_user }}"
    group: "{{ terraform_user }}"
  tags: terraform:config

- name: Inclui tarefas do TFLint
  include_tasks: tflint.yml
  when: terraform_tflint_install
  tags: terraform:tflint

- name: Inclui tarefas do terraform-docs
  include_tasks: terraform-docs.yml
  when: terraform_docs_install
  tags: terraform:docs

# Graphviz é útil para visualização do 'terraform graph'
# Docs: https://www.terraform.io/docs/commands/graph.html#generating-images
- name: Instala Graphviz
  apt:
    name: graphviz
    state: present
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
  when: terraform_graphviz_install
  tags: terraform:graphviz
