---
- name: Verifica se TFLint {{ terraform_tflint_version }} está instalado
  shell: tflint --version || true
  register: terraform_tflint_check
  changed_when: false

- name: Instala TFLint
  unarchive:
    remote_src: true
    src: "{{ terraform_tflint_dl_url }}"
    dest: "{{ terraform_tflint_path | dirname }}"
    owner: root
    group: root
    mode: "0755"
  when: >
    terraform_tflint_check.stdout_lines | length == 0
    or terraform_tflint_version not in terraform_tflint_check.stdout_lines[0]
