---
- name: Verifica se Borg {{ borg_version }} está instalado
  shell: borg --version || true
  register: borg_check
  changed_when: false

- name: Instala Borg
  get_url:
    url: "{{ borg_dl_url }}"
    dest: "{{ borg_path }}"
    checksum: sha256:{{ borg_sha256_checksum }}
    owner: root
    group: root
    mode: "0755"
  when: >
    borg_check.stdout_lines | length == 0
    or borg_version not in borg_check.stdout_lines[0]
