---
- name: Check if v{{ chef_workstation_version }} is installed
  ansible.builtin.shell: >
    dpkg-query --showformat='${Version}' --show chef-workstation || true
  register: chef_workstation_check
  changed_when: false

- name: Install Chef Workstation
  ansible.builtin.apt:
    deb: "{{ chef_workstation_package_url }}"
    state: present
    install_recommends: false
  when: chef_workstation_check.stdout != chef_workstation_version_deb
