---
- name: Create installation directory
  ansible.builtin.file:
    path: "{{ dotfiles_install_dir }}"
    state: directory
    owner: "{{ dotfiles_user }}"
    group: "{{ dotfiles_user }}"
    mode: "0755"

- name: Install dotfiles
  become: true
  become_user: "{{ dotfiles_user }}"
  block:
    - name: Clone/update repository
      ansible.builtin.git:
        repo: "{{ dotfiles_git_repo }}"
        dest: "{{ dotfiles_install_dir }}"
        version: "{{ dotfiles_git_version }}"
        update: "{{ dotfiles_git_update }}"

    - name: Install dotfiles
      ansible.builtin.file:
        src: "{{ item }}"
        dest: "{{ dotfiles_home }}/.{{ item | basename }}"
        force: true
        state: link
      loop: "{{ lookup('fileglob', dotfiles_files_glob, wantlist=True) | sort }}"
