---
- name: Check if helm-docs {{ helm_docs_version }} is installed
  shell: helm-docs --version || true
  register: helm_docs_check
  changed_when: false

- name: Install helm-docs
  unarchive:
    remote_src: true
    src: "{{ helm_docs_dl_url }}"
    dest: "{{ helm_docs_path | dirname }}"
    extra_opts:
      - helm-docs  # Extract only the binary
    owner: root
    group: root
    mode: 0755
  when: >
    helm_docs_check.stdout_lines | length == 0
    or helm_docs_version not in helm_docs_check.stdout_lines[0]
