---
- name: Check if restic {{ restic_version }} is installed
  ansible.builtin.shell: restic version || true
  register: restic_check
  changed_when: false
  tags: restic:install

- name: Run installation tasks
  when: >
    restic_check.stdout_lines | length == 0
    or ("restic " + restic_version + " compiled") not in restic_check.stdout_lines[0]
  block:
    - name: Download files
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        force: true
        owner: root
        group: root
        mode: "0644"
      loop:
        - url: "{{ restic_archive_url }}"
          dest: "{{ restic_archive_file }}"
        - url: "{{ restic_sha256sums_url }}"
          dest: "{{ restic_sha256sums_file }}"
      tags: restic:install

    - name: Check integrity of the downloaded archive
      ansible.builtin.shell: >
        cat '{{ restic_sha256sums_file }}' | sha256sum --check --ignore-missing
      args:
        chdir: "{{ restic_archive_file | dirname }}"
      tags: restic:install

    - name: Extract binary from the archive
      ansible.builtin.shell: >
        bzip2 --decompress --stdout {{ restic_archive_file }} > {{ restic_bin_path }}
      tags: restic:install

    - name: Ensure binary has the right permissions
      ansible.builtin.file:
        path: "{{ restic_bin_path }}"
        state: file
        owner: root
        group: root
        mode: "0755"
      tags: restic:install

    - name: Configure Bash completion
      ansible.builtin.command: >
        restic generate --bash-completion /etc/bash_completion.d/restic
      when: restic_configure_completion
      tags: restic:config
