---
- name: Verifica se Vagrant {{ vagrant_version }} está instalado
  shell: dpkg-query --showformat='${Version}' --show vagrant || true
  register: vagrant_check
  changed_when: false
  tags: vagrant:install

- name: Instala Vagrant
  apt:
    deb: "{{ vagrant_package_url }}"
    state: present
    install_recommends: false
  when: vagrant_check.stdout[2:] != vagrant_version
  tags: vagrant:install

- name: Inclui tarefas de plugins
  import_tasks: plugins.yml
  tags: vagrant:plugins
