---
- name: Verifica se Packer {{ packer_version }} está instalado
  shell: packer version || true
  register: packer_check
  changed_when: false

- name: Instala Packer
  unarchive:
    remote_src: true
    src: "{{ packer_dl_url }}"
    dest: "{{ packer_path | dirname }}"
    owner: root
    group: root
    mode: "0755"
  when: >
    packer_check.stdout_lines | length == 0
    or packer_version not in packer_check.stdout_lines[0]

- name: Configura Bash completion
  copy:
    content: >
      complete -C {{ packer_path }} packer
    dest: /etc/bash_completion.d/packer
    owner: root
    group: root
    mode: "0644"
  when: packer_enable_bash_completion
  tags: packer:completion
