---
- name: Install repository key
  ansible.builtin.get_url:
    url: "{{ vscode_apt_repo_key_url }}"
    dest: "{{ vscode_apt_repo_key_file }}"
    force: true
    owner: root
    group: root
    mode: "0644"
  tags:
    - vscode:repo
    - vscode:install

- name: Configure repository
  ansible.builtin.apt_repository:
    repo: "{{ vscode_apt_repo_line }}"
    filename: "{{ vscode_apt_repo_file }}"
    state: present
    update_cache: true
  tags:
    - vscode:repo
    - vscode:install

- name: Setup debconf to avoid repository changes by the package itself
  ansible.builtin.debconf:
    name: code
    question: code/add-microsoft-repo
    vtype: boolean
    value: "false"
  tags:
    - vscode:repo
    - vscode:install

- name: Install packages
  ansible.builtin.apt:
    name: code
    state: present
    install_recommends: false
  tags: vscode:install
