---
- name: Verifica se ctop {{ ctop_version }} está instalado
  shell: ctop -v || true
  register: ctop_check
  changed_when: false

- name: Instala ctop
  get_url:
    url: "{{ ctop_dl_url }}"
    dest: "{{ ctop_path }}"
    force: true
    owner: root
    group: root
    mode: "0755"
  when: >
    ctop_check.stdout_lines | length == 0
    or ctop_version not in ctop_check.stdout
