---
- name: Check if infracost {{ infracost_version }} is installed
  shell: infracost --version || true
  register: infracost_check
  changed_when: false

- name: Install infracost
  unarchive:
    remote_src: true
    src: "{{ infracost_dl_url }}"
    dest: "{{ infracost_path | dirname }}"
    extra_opts:
      - --transform
      - s/-linux-amd64//
    owner: root
    group: root
    mode: "0755"
  when: >
    infracost_check.stdout_lines | length == 0
    or infracost_version not in infracost_check.stdout_lines[0]

- name: Configure Bash completion
  shell: >
    infracost completion --shell bash > /etc/bash_completion.d/infracost
  when: >
    infracost_check.stdout_lines | length == 0
    or infracost_version not in infracost_check.stdout_lines[0]
