---
restic_version: 0.14.0

restic_dl_url: >-
  https://github.com/restic/restic/releases/download/v{{ restic_version }}/restic_{{ restic_version }}_linux_amd64.bz2

restic_sha256_checksum: c8da7350dc334cd5eaf13b2c9d6e689d51e7377ba1784cc6d65977bd44ee1165

restic_path: /usr/local/bin/restic

restic_man_pages_dir: /usr/local/share/man/man1
