---
- name: Verifica se jq {{ jq_version }} está instalado
  shell: jq --version || true
  register: jq_check
  changed_when: false

- name: Executa tarefas de instalação
  when: >
    jq_check.stdout_lines | length == 0
    or jq_version not in jq_check.stdout
  block:
    - name: Instala jq
      get_url:
        url: "{{ jq_dl_url }}"
        dest: "{{ jq_path }}"
        force: true
        owner: root
        group: root
        mode: "0755"

    - name: Cria diretório de man pages
      file:
        path: "{{ jq_man_path | dirname }}"
        state: directory
        owner: root
        group: root

    - name: Instala man page
      get_url:
        url: "{{ jq_man_dl_url }}"
        dest: "{{ jq_man_path }}"
        force: true
        owner: root
        group: root
