---
- name: Install repository key
  apt_key:
    url: "{{ virtualbox_repo_key_url }}"
    state: present
    keyring: "{{ virtualbox_repo_key_file }}"
  tags:
    - virtualbox:repo
    - virtualbox:install

- name: Configure repository
  apt_repository:
    repo: "{{ virtualbox_repo_line }}"
    filename: "{{ virtualbox_repo_file }}"
    state: present
    update_cache: false
  tags:
    - virtualbox:repo
    - virtualbox:install

- name: Install packages
  apt:
    name:
      - virtualbox-{{ virtualbox_version_major }}
      - libsdl-ttf2.0-0
    state: present
    install_recommends: false
    update_cache: true
  tags: virtualbox:install

- name: Add user to 'vboxusers' group
  user:
    name: "{{ virtualbox_user }}"
    groups: vboxusers
    append: true
  tags: virtualbox:install

- name: Run Extension Pack tasks
  import_tasks: extpack.yml
  tags: virtualbox:extpack
