---
- name: Check if version {{ q_version }} is installed
  ansible.builtin.shell: dpkg-query --showformat='${Version}' --show q-text-as-data || true
  register: q_check
  changed_when: false

- name: Install package
  ansible.builtin.apt:
    deb: "{{ q_package_url }}"
    state: present
    install_recommends: false
  when: q_check.stdout != q_version
