---
- name: Check if kubespy {{ kubespy_version }} is installed
  shell: kubespy version || true
  register: kubespy_check
  changed_when: false

- name: Install kubespy
  unarchive:
    remote_src: true
    src: "{{ kubespy_dl_url }}"
    dest: "{{ kubespy_path | dirname }}"
    extra_opts:
      - kubespy  # Extract only the binary
    owner: root
    group: root
    mode: 0755
  when: >
    kubespy_check.stdout_lines | length == 0
    or kubespy_version not in kubespy_check.stdout_lines[0]
