---
- name: Ensure config directory exists
  ansible.builtin.file:
    path: "{{ resticprofile_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create config file
  ansible.builtin.template:
    src: profiles.yaml.j2
    dest: "{{ resticprofile_config_file }}"
    owner: root
    group: root
    mode: "0644"
    lstrip_blocks: true
