---
- name: Ensure all utilities are installed
  pip:
    name: "{{ item.1.name | default(item.1) }}"
    version: "{{ item.1.version | default(omit) }}"
    state: present
    virtualenv: "{{ piputils_install_dir }}/{{ item.0.name }}"
    virtualenv_python: "{{ item.0.python | default('python3') }}"
  loop: "{{ piputils_packages | subelements('packages') }}"
  when: item.0.name not in piputils_uninstall_package_names

- name: Ensure all utilities' symlinks exist
  file:
    src: "{{ piputils_install_dir }}/{{ item.0.name }}/bin/{{ item.1 }}"
    path: "{{ piputils_bin_symlink_dir }}/{{ item.1 }}"
    state: link
    force: false
  loop: "{{ piputils_packages | subelements('binaries') }}"
  when: item.0.name not in piputils_uninstall_package_names
