---
- name: Verifica se Keybase está instalado
  shell: dpkg-query --showformat='${Version}' --show keybase || true
  register: keybase_check
  changed_when: false

- name: Instala Keybase
  apt:
    deb: "{{ keybase_package_url }}"
    state: present
    install_recommends: false
  when: "'no packages found matching' in keybase_check.stderr"

- name: Desativa inicialização automática
  command: keybase ctl autostart --disable
  become: true
  become_user: "{{ keybase_user }}"
  changed_when: false
  when: keybase_disable_autostart
