---
# Global

desktop_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
desktop_home_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}"
desktop_config_dir: "{{ desktop_home_dir }}/.config"

# Autostart

desktop_autostart_dir: "{{ desktop_config_dir }}/autostart"

desktop_autostart_disable_apps:
  - blueman
  - update-notifier

# User dirs

desktop_user_dirs_base_dir: "{{ desktop_home_dir }}"

desktop_user_dirs:
  - name: DESKTOP
    path: Desktop
  - name: DOWNLOAD
    path: cache
  - name: TEMPLATES
    path: library/Templates
  - name: PUBLICSHARE
    path: library/Public
  - name: DOCUMENTS
    path: library/Documents
  - name: MUSIC
    path: library/Music
  - name: PICTURES
    path: library/Pictures
  - name: VIDEOS
    path: library/Videos

desktop_remove_default_user_dirs: false

# Bookmarks

desktop_bookmarks_file: "{{ desktop_config_dir }}/gtk-3.0/bookmarks"

desktop_bookmarks:
  - /arquivos
  - "{{ desktop_home_dir }}/cache"
  - "{{ desktop_home_dir }}/projects"

# Xfconf

desktop_xfconf_settings:
  # Thunar
  - channel: thunar
    property: /last-location-bar
    value: ThunarLocationButtons
    value_type: string
  - channel: thunar
    property: /last-menubar-visible
    value: "false"
    value_type: bool
  - channel: thunar
    property: /last-sort-column
    value: THUNAR_COLUMN_TYPE
    value_type: string
  - channel: thunar
    property: /last-sort-order
    value: GTK_SORT_ASCENDING
    value_type: string
  - channel: thunar
    property: /last-view
    value: ThunarDetailsView
    value_type: string
  - channel: thunar
    property: /last-window-maximized
    value: "true"
    value_type: bool
  - channel: thunar
    property: /misc-change-window-icon
    value: "true"
    value_type: bool
  - channel: thunar
    property: /misc-date-style
    value: THUNAR_DATE_STYLE_LONG
    value_type: string
  - channel: thunar
    property: /misc-full-path-in-title
    value: "false"
    value_type: bool
  - channel: thunar
    property: /misc-open-new-window-as-tab
    value: "true"
    value_type: bool
  - channel: thunar
    property: /misc-thumbnail-mode
    value: THUNAR_THUMBNAIL_MODE_ONLY_LOCAL
    value_type: string
  - channel: thunar
    property: /misc-folders-first
    value: "true"
    value_type: bool
  - channel: thunar
    property: /misc-volume-management
    value: "false"
    value_type: bool
  - channel: thunar
    property: /shortcuts-icon-size
    value: THUNAR_ICON_SIZE_24
    value_type: string

  # Desktop
  - channel: xfce4-desktop
    property: /desktop-icons/style
    value: "0"
    value_type: int
  - channel: xfce4-desktop
    property: /desktop-menu/show
    value: "true"
    value_type: bool
  - channel: xfce4-desktop
    property: /desktop-menu/show-icons
    value: "true"
    value_type: bool
  - channel: xfce4-desktop
    property: /windowlist-menu/show
    value: "false"
    value_type: bool

  # Window Manager
  - channel: xfwm4
    property: /general/button_layout
    value: "CMH|O"
    value_type: string

# Keyboard shortcuts
# See 'defaults/main/keyboard-shortcuts.yml'.

# Packages

desktop_packages:
  - oxygen-cursor-theme
  - tumbler
