---
- name: Check if OPA {{ opa_version }} is installed
  shell: opa version || true
  register: opa_check
  changed_when: false

- name: Install OPA
  get_url:
    url: "{{ opa_dl_url }}"
    dest: "{{ opa_path }}"
    force: true
    owner: root
    group: root
    mode: 0755
  when: >
    opa_check.stdout_lines | length == 0
    or opa_version not in opa_check.stdout
