---
# Usuário do sistema
# Padrão: $USER (do usuário que executa o Ansible)
vagrant_user: "{{ lookup('ansible.builtin.env', 'USER') }}"

vagrant_version: 2.3.0

vagrant_package_url: >-
  https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_{{ ansible_architecture }}.deb

vagrant_plugins:
  - vagrant-digitalocean
  - vagrant-hostsupdater

vagrant_update_plugins: true
