---
- name: Workstation - Base System
  hosts: all

  roles:
    - role: packages
      tags: packages
    - role: base-system
      tags: base-system
    - role: firefox
      tags: firefox
    - role: xubuntu-desktop
      tags: xubuntu-desktop
