---
- name: Buffer test
  hosts: all
  gather_facts: false

  tasks:
    - name: Buffer test
      shell: >-
        for i in {1..5} ; do echo "Hey" ; sleep 1 ; done
      args:
        executable: /bin/bash
