---
- name: Install repository key
  ansible.builtin.get_url:
    url: "{{ spotify_apt_repo_key_url }}"
    dest: "{{ spotify_apt_repo_key_file }}"
    force: true
    owner: root
    group: root
    mode: "0644"
  tags:
    - spotify:repo
    - spotify:install

- name: Configure repository
  ansible.builtin.apt_repository:
    repo: "{{ spotify_apt_repo_line }}"
    filename: "{{ spotify_apt_repo_file }}"
    state: present
    update_cache: true
  tags:
    - spotify:repo
    - spotify:install

- name: Install packages
  ansible.builtin.apt:
    name:
      - spotify-client
      - libavcodec-extra
    state: present
    install_recommends: false
  tags: spotify:install
