---
- name: Include autostart tasks
  ansible.builtin.import_tasks: autostart.yml
  tags: xubuntu-desktop:autostart

- name: Include user dir tasks
  ansible.builtin.import_tasks: user-dirs.yml
  tags: xubuntu-desktop:user-dirs

- name: Include bookmark tasks
  ansible.builtin.import_tasks: bookmarks.yml
  tags: xubuntu-desktop:bookmarks

- name: Include keyboard shortcuts tasks
  ansible.builtin.import_tasks: keyboard-shortcuts.yml
  become: true
  become_user: "{{ desktop_user }}"
  tags: xubuntu-desktop:keyboard-shortcuts

- name: Apply Xfconf settings
  community.general.xfconf:
    channel: "{{ item.channel }}"
    property: "{{ item.property }}"
    value: "{{ item.value }}"
    value_type: "{{ item.value_type | default('string') }}"
    state: present
  loop: "{{ desktop_xfconf_settings }}"
  become: true
  become_user: "{{ desktop_user }}"
  tags: xubuntu-desktop:xfconf

- name: Install defined packages
  ansible.builtin.apt:
    name: "{{ desktop_packages }}"
    state: present
    install_recommends: false
  tags: xubuntu-desktop:packages

- name: Define Oxygen Zion as cursor theme (alternatives)
  community.general.alternatives:
    name: x-cursor-theme
    path: /etc/X11/cursors/oxy-zion.theme
  when: >
    'oxygen-cursor-theme' in desktop_packages
  tags: xubuntu-desktop:cursor

- name: Define Oxygen Zion as cursor theme (xsettings)
  community.general.xfconf:
    channel: xsettings
    property: /Gtk/CursorThemeName
    value: oxy-zion
    value_type: string
    state: present
  when: >
    'oxygen-cursor-theme' in desktop_packages
  become: true
  become_user: "{{ desktop_user }}"
  tags: xubuntu-desktop:cursor
