---
- import_tasks: autostart.yml
  tags: xubuntu-desktop:autostart

- import_tasks: user-dirs.yml
  tags: xubuntu-desktop:user-dirs

- import_tasks: bookmarks.yml
  tags: xubuntu-desktop:bookmarks

- import_tasks: keyboard-shortcuts.yml
  become: true
  become_user: "{{ desktop_user }}"
  tags: xubuntu-desktop:keyboard-shortcuts

- name: Configura ambiente via Xfconf
  xfconf:
    channel: "{{ item.channel }}"
    property: "{{ item.property }}"
    value: "{{ item.value }}"
    value_type: "{{ item.value_type | default('string') }}"
    state: present
  loop: "{{ desktop_xfconf_settings }}"
  become: true
  become_user: "{{ desktop_user }}"
  tags: xubuntu-desktop:xfconf

- name: Instala pacotes selecionados
  apt:
    name: "{{ desktop_packages }}"
    state: present
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
  tags: xubuntu-desktop:packages

- name: Define Oxygen Zion como tema do cursor do mouse (alternatives)
  alternatives:
    name: x-cursor-theme
    path: /etc/X11/cursors/oxy-zion.theme
  when: >
    'oxygen-cursor-theme' in desktop_packages
  tags: xubuntu-desktop:cursor

- name: Define Oxygen Zion como tema do cursor do mouse (xsettings)
  xfconf:
    channel: xsettings
    property: /Gtk/CursorThemeName
    value: oxy-zion
    value_type: string
    state: present
  when: >
    'oxygen-cursor-theme' in desktop_packages
  become: true
  become_user: "{{ desktop_user }}"
  tags: xubuntu-desktop:cursor
